
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BROWSER_ARG OPERATE PAGE WEBBROWSERcommand : OPERATE WEBBROWSER\n               | OPERATE WEBBROWSER BROWSER_ARG\n               | OPERATE WEBBROWSER BROWSER_ARG PAGE'
    
_lr_action_items = {'OPERATE':([0,],[2,]),'$end':([1,3,4,5,],[0,-1,-2,-3,]),'WEBBROWSER':([2,],[3,]),'BROWSER_ARG':([3,],[4,]),'PAGE':([4,],[5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'command':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> command","S'",1,None,None,None),
  ('command -> OPERATE WEBBROWSER','command',2,'p_command','browser.py',58),
  ('command -> OPERATE WEBBROWSER BROWSER_ARG','command',3,'p_command','browser.py',59),
  ('command -> OPERATE WEBBROWSER BROWSER_ARG PAGE','command',4,'p_command','browser.py',60),
]
